---
permalink: audit/object-storage-audit-messages.html 
sidebar: sidebar 
keywords: storagegrid, audit, object storage, object management, object retrieval, node transfer, verification, APCT, ARCB, ARCE, ARCT, AREM, ASCE, ASCT, ATCE, AVCC, CBSE, CBRE, SCMT, SREM 
summary: 您应熟悉属于对象存储审核类别的审核消息。这些事件与 StorageGRID 系统中对象的存储和管理相关。其中包括对象存储和检索，网格节点到网格节点的传输以及验证。 
---
= 对象存储审核消息
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您应熟悉属于对象存储审核类别的审核消息。这些事件与 StorageGRID 系统中对象的存储和管理相关。其中包括对象存储和检索，网格节点到网格节点的传输以及验证。

|===
| 代码 | Description | 请参见 


 a| 
APCT
 a| 
从云层清除归档：已归档的对象数据将从外部归档存储系统中删除，该系统通过 S3 API 连接到 StorageGRID 。
 a| 
link:apct-archive-purge-from-cloud-tier.html["APCT ：从云层清除归档"]



 a| 
ARCB
 a| 
归档对象检索开始： ARC-Service 开始从外部归档存储系统检索对象数据。
 a| 
link:arcb-archive-object-retrieve-begin.html["ARCB ：开始归档对象检索"]



 a| 
Arce
 a| 
归档对象检索结束：对象数据已从外部归档存储系统中检索，并且 ARC-Service 会报告检索操作的状态。
 a| 
link:arce-archive-object-retrieve-end.html["Arce ：归档对象检索结束"]



 a| 
ARCT
 a| 
从云层检索归档：归档对象数据从外部归档存储系统中检索，该系统通过 S3 API 连接到 StorageGRID 。
 a| 
link:arct-archive-retrieve-from-cloud-tier.html["ARCT ：从云层检索归档"]



 a| 
AREM
 a| 
归档对象删除：已从外部归档存储系统成功或未成功删除内容块。
 a| 
link:arem-archive-object-remove.html["AREM ：归档对象删除"]



 a| 
ASCE
 a| 
归档对象存储结束：已将内容块写入外部归档存储系统，并且 ARC-Service 会报告写入操作的状态。
 a| 
link:asce-archive-object-store-end.html["ASCE ：归档对象存储结束"]



 a| 
上一个月
 a| 
归档存储云层：对象数据存储到外部归档存储系统，该系统通过 S3 API 连接到 StorageGRID 。
 a| 
link:asct-archive-store-cloud-tier.html["SCT ：归档存储云层"]



 a| 
ATCE
 a| 
归档对象存储开始：已开始向外部归档存储写入内容块。
 a| 
link:atce-archive-object-store-begin.html["ATCE ：开始归档对象存储"]



 a| 
AVCC
 a| 
归档验证云层配置：提供的帐户和存储分段设置已成功验证或未成功验证。
 a| 
link:avcc-archive-validate-cloud-tier-configuration.html["AVCC ：归档验证云层配置"]



 a| 
CBSE
 a| 
对象发送结束：源实体完成了网格节点到网格节点的数据传输操作。
 a| 
link:cbse-object-send-end.html["CBSE ：对象发送结束"]



 a| 
CBRE
 a| 
对象接收结束：目标实体完成了网格节点到网格节点的数据传输操作。
 a| 
link:cbre-object-receive-end.html["CBRE ：对象接收结束"]



 a| 
SCMT
 a| 
对象存储提交：内容块已完全存储和验证，现在可以请求。
 a| 
link:scmt-object-store-commit.html["SCMT ：对象存储提交"]



 a| 
Srem
 a| 
对象存储删除：已从网格节点中删除内容块，无法再直接请求。
 a| 
link:srem-object-store-remove.html["Srem ：对象存储删除"]

|===