---
permalink: upgrade/estimating-time-to-complete-upgrade.html 
sidebar: sidebar 
keywords: upgrade, time estimate, duration, cassandra upgrade 
summary: 在计划升级到StorageGRID 11.5时、您必须根据升级可能需要的时间考虑何时进行升级。此外，您还必须了解在升级的每个阶段可以执行哪些操作，哪些操作不能执行。 
---
= 估计完成升级所需的时间
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在计划升级到StorageGRID 11.5时、您必须根据升级可能需要的时间考虑何时进行升级。此外，您还必须了解在升级的每个阶段可以执行哪些操作，哪些操作不能执行。

.关于此任务
完成 StorageGRID 升级所需的时间取决于多种因素，例如客户端负载和硬件性能。

下表汇总了主要升级任务，并列出了每个任务所需的大致时间。下表后面的步骤提供了一些说明，您可以使用这些说明来估计系统的升级时间。


IMPORTANT: 在从StorageGRID 11.4升级到11.5期间、存储节点上的Cassandra数据库表将升级。升级数据库*任务在后台执行、但可能需要大量时间才能完成。在升级数据库时、您可以安全地使用新功能、应用修补程序并执行节点恢复操作。但是、您可能无法执行其他维护过程。


NOTE: 如果迫切需要扩展、请先执行扩展、然后再升级到11.5。

[cols="1a,1a,1a,a"]
|===
| 升级任务 | Description | 所需大致时间 | 执行此任务期间 


 a| 
启动升级服务
 a| 
运行升级预检，分发软件文件并启动升级服务。
 a| 
每个网格节点 3 分钟，除非报告验证错误
 a| 
根据需要，您可以在计划的升级维护窗口之前手动运行升级预检。



 a| 
升级网格节点（主管理节点）
 a| 
主管理节点将停止，升级并重新启动。
 a| 
最长30分钟
 a| 
您无法访问主管理节点。系统会报告连接错误，您可以忽略这些错误。



 a| 
升级网格节点（所有其他节点）
 a| 
所有其他网格节点上的软件将按照您批准节点的顺序进行升级。系统中的每个节点将逐个关闭，每个节点将停机几分钟。
 a| 
每个节点15到45分钟、其中设备存储节点所需时间最长

* 注： * 对于设备节点， StorageGRID 设备安装程序会自动更新到最新版本。
 a| 
* 请勿更改网格配置。
* 请勿更改审核级别配置。
* 请勿更新 ILM 配置。
* 请勿执行其他维护操作步骤 、例如修补程序、停用或扩展。
+
*注：*如果需要执行恢复操作步骤 、请联系技术支持。





 a| 
启用功能
 a| 
新版本的新功能已启用。
 a| 
不到 5 分钟
 a| 
* 请勿更改网格配置。
* 请勿更改审核级别配置。
* 请勿更新 ILM 配置。
* 请勿执行其他维护操作步骤。




 a| 
升级数据库
 a| 
所有存储节点上的Cassandra数据库表都会进行升级。
 a| 
小时或天、具体取决于系统中的元数据量
 a| 
在*升级数据库*任务期间、升级后的网格将正常运行；但是、升级仍将进行。在此任务期间、您可以：

* 使用新StorageGRID 版本中的新功能。
* 更改审核级别配置。
* 更新ILM配置。
* 应用修补程序。
* 恢复节点。


*注意：*在*最终升级步骤*完成之前、无法执行停用或扩展操作步骤。



 a| 
最终升级步骤
 a| 
此时将删除临时文件，并完成到新版本的升级。
 a| 
5 分钟
 a| 
完成 * 最终升级步骤 * 任务后，您可以执行所有维护过程。

|===
.步骤
. 估计升级所有网格节点所需的时间(考虑除*升级数据库*之外的所有升级任务)。
+
.. 将StorageGRID 系统中的节点数乘以每个节点30分钟(平均值)。
.. 在此时间加上1小时、以考虑下载所需的时间 `.upgrade` 文件、运行预检验证并完成最终升级步骤。


. 如果您使用的是 Linux 节点，请为每个节点添加 15 分钟的时间，以考虑下载和安装 RPM 或 Deb 软件包所需的时间。
. 估计升级数据库所需的时间。
+
.. 在网格管理器中、选择*节点*。
.. 选择树中的第一个条目(整个网格)、然后选择*存储*选项卡。
.. 将光标悬停在*已用存储-对象元数据*图表上、找到*已用*值、该值表示网格中的对象元数据字节数。
.. 将*已用*值除以1.5 TB/天、以确定升级数据库需要多少天。


. 通过添加步骤1、2和3的结果来计算升级的总估计时间。




== 示例：估计从StorageGRID 11.4升级到11.5所需的时间

假设您的系统有 14 个网格节点，其中 8 个是 Linux 节点。此外、假设对象元数据的*已用*值为6 TB。

. 将每个节点的14乘以30分钟、再增加1小时。升级所有节点的估计时间为8小时。
. 每个节点需要8到15分钟、以说明在Linux节点上安装RPM或Deb软件包的时间。此步骤的估计时间为 2 小时。
. 除以6除以1.5 TB/天。*升级数据库*任务的估计天数为4天。
+

NOTE: 在运行*升级数据库*任务时、您可以安全地使用新功能、应用修补程序并执行节点恢复操作。

. 将这些值相加。您应留出5天的时间来完成系统到StorageGRID 11.5.0的升级。

