---
permalink: upgrade/how-your-system-is-affected-during-upgrade.html 
sidebar: sidebar 
keywords: upgrade, firmware, appliance, alert 
summary: 您必须了解 StorageGRID 系统在升级期间会受到什么影响。 
---
= 升级期间对系统的影响
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您必须了解 StorageGRID 系统在升级期间会受到什么影响。



== StorageGRID 升级不会造成系统中断

StorageGRID 系统可以在整个升级过程中从客户端应用程序载入和检索数据。在升级期间，网格节点会一次关闭一个，因此，目前并非所有网格节点都不可用。

要保证持续可用性，您必须确保使用适当的 ILM 策略以冗余方式存储对象。此外，您还必须确保将所有外部 S3 或 Swift 客户端配置为向以下客户端之一发送请求：

* 配置为高可用性（ HA ）组的 StorageGRID 端点
* 高可用性第三方负载平衡器
* 每个客户端具有多个网关节点
* 每个客户端具有多个存储节点




== 设备固件已升级

在StorageGRID 11.5升级期间：

* 所有StorageGRID 设备节点都会自动升级到StorageGRID 设备安装程序固件版本3.5。
* SG6060和SGF6024设备会自动升级到BIOS固件版本3B03.EX和BMC固件版本BMC 3.90.07。
* SG100和SG1000设备会自动升级到BIOS固件版本3B08.EC和BMC固件版本4.64.07。




== 可能会触发警报

服务启动和停止以及 StorageGRID 系统作为混合版本环境运行时（某些网格节点运行早期版本，而其他网格节点已升级到更高版本），可能会触发警报。例如、服务停止时、您可能会看到*无法与节点*通信警报；或者、如果某些节点已升级到StorageGRID 11.5、但其他节点仍在运行StorageGRID 11.4、则可能会看到* Cassandra communication error*警报。

通常，这些警报将在升级完成后清除。

升级完成后、您可以从网格管理器信息板中选择*最近解决的警报*来查看任何与升级相关的警报。


NOTE: 在升级到StorageGRID 11.5期间、如果存储节点停止、则可能会触发"ILM placement unalableable*"警报。升级成功完成后、此警报可能会持续1天。



== 系统会生成许多 SNMP 通知

请注意，在升级期间停止并重新启动网格节点时，可能会生成大量 SNMP 通知。要避免出现过多通知、请在开始升级之前取消选中*启用SNMP代理通知*复选框(*配置*>*监控*>* SNMP代理*)以禁用SNMP通知。然后，在升级完成后重新启用通知。



== 配置更改受限

直到 * 启用新功能 * 任务完成：

* 请勿更改任何网格配置。
* 请勿更改审核级别配置。
* 请勿启用或禁用任何新功能。
* 请勿更新 ILM 配置。否则，您可能会遇到不一致的意外 ILM 行为。
* 请勿应用修补程序或恢复网格节点。


完成 * 最终升级步骤 * 任务之前：

* 请勿执行扩展操作步骤 。
* 请勿执行停用操作步骤 。

