---
permalink: upgrade/whats-new.html 
sidebar: sidebar 
keywords: new features, 11.5, object lock, kmip, kms, ilm, decommission, node clone 
summary: StorageGRID 11.5引入了S3对象锁定、支持KMIP数据加密、ILM的可用性改进、重新设计的租户管理器用户界面、支持停用StorageGRID 站点以及设备节点克隆操作步骤。 
---
= StorageGRID 11.5中的新增功能
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID 11.5引入了S3对象锁定、支持KMIP数据加密、ILM的可用性改进、重新设计的租户管理器用户界面、支持停用StorageGRID 站点以及设备节点克隆操作步骤。



== 兼容数据的S3对象锁定

StorageGRID 11.5中的S3对象锁定功能是一种对象保护解决方案 、相当于Amazon Simple Storage Service (Amazon S3)中的S3对象锁定。您可以为 StorageGRID 系统启用全局 S3 对象锁定设置，以允许 S3 租户帐户在启用了 S3 对象锁定的情况下创建分段。然后、租户可以使用S3客户端应用程序为这些分段中的对象指定保留和合法保留设置。

S3对象锁定允许租户用户遵守相关法规、这些法规要求将某些对象保留固定时间或无限期。

.了解更多信息。
* link:../ilm/index.html["使用 ILM 管理对象"]
* link:../s3/index.html["使用 S3"]
* link:../tenant/index.html["使用租户帐户"]




== Kms加密密钥管理

现在、您可以在网格管理器中配置一个或多个外部密钥管理服务器(KMS)、以便为StorageGRID 服务和存储设备提供加密密钥。每个 KMS 或 KMS 集群都使用密钥管理互操作性协议（ Key Management Interoperability Protocol ， KMIP ）为关联 StorageGRID 站点上的设备节点提供一个加密密钥。对设备卷进行加密后，除非节点可以与 KMS 通信，否则无法访问设备上的任何数据。


NOTE: 如果要使用加密密钥管理、必须先使用StorageGRID 设备安装程序为设备启用*节点加密*设置、然后再将设备添加到网格中。

.了解更多信息。
* link:../admin/index.html["管理 StorageGRID"]




== 信息生命周期管理(ILM)的可用性增强功能

* 现在、您可以查看存储池的总容量、包括已用空间量和可用空间量。此外、您还可以查看存储池中包含哪些节点、以及哪些ILM规则和纠删编码配置文件使用存储池。
* 现在、您可以设计适用于多个租户帐户的ILM规则。
* 创建纠删编码的ILM规则时、系统会提醒您将对象大小(MB)高级筛选器设置为大于0.2的值、以确保非常小的对象不会进行纠删编码。
* 现在、ILM策略界面可确保默认ILM规则始终用于其他规则不匹配的任何对象。从StorageGRID 11.5开始、默认规则不能使用任何基本筛选器或高级筛选器、它会自动作为策略中的最后一条规则放置。
+

NOTE: 如果您当前的ILM策略不符合新要求、则可以在升级到StorageGRID 11.5后继续使用它。但是、如果您在升级后尝试克隆不符合策略、则系统会提示您选择一个不包含筛选器的默认规则、您需要将此默认规则置于策略末尾。

* 默认情况下、在创建新的ILM规则或新的纠删编码配置文件时、系统将不再选择所有存储节点存储池。此外、您现在可以删除所有存储节点存储池、只要它未在任何规则中使用即可。
+

NOTE: 建议不要使用所有存储节点存储池、因为此存储池包含所有站点。如果将某个对象的多个副本用于包含多个站点的StorageGRID 系统、则可以将此存储池放置在同一站点上。

* 现在、只要当前策略或建议的策略中未使用此常用创建2个副本规则(该规则使用所有存储节点存储池)、您就可以将其删除。
* 现在、可以立即删除存储在云存储池中的对象(同步删除)。


.了解更多信息。
* link:../ilm/index.html["使用 ILM 管理对象"]




== 网格管理器的增强功能

* 通过重新设计的租户帐户页面、可以更轻松地查看租户帐户使用情况。租户摘要表现在包含已用空间、配额利用率、配额和对象计数列。一个新的*查看详细信息*按钮用于访问每个租户的概况以及有关帐户的S3分段或Swift容器的详细信息。此外、您现在还可以导出两个 `.csv` 租户使用的文件：一个包含所有租户的使用值、一个包含租户的分段或容器的详细信息。
+
与此更改相关的是、添加了三个新的Prometheus指标来跟踪租户帐户使用情况：

+
** `storagegrid_tenant_usage_data_bytes`
** `storagegrid_tenant_usage_object_count`
** `storagegrid_tenant_usage_quota_bytes`


* 通过管理组页面(*配置*>*访问控制*)上的新*访问模式*字段、您可以指定组的管理权限是读写(默认)还是只读。属于具有读写访问模式的组的用户可以在网格管理器和网格管理API中更改设置并执行操作。属于具有只读访问模式的组的用户只能查看为该组选择的设置和功能。
+

NOTE: 升级到StorageGRID 11.5时、系统会为所有现有管理组选择读写访问模式选项。

* AutoSupport 用户界面经过重新设计。现在、您可以从网格管理器的单个页面配置事件触发、用户触发和每周AutoSupport 消息。您还可以为AutoSupport 消息配置一个额外的目标。
+

NOTE: 如果尚未启用AutoSupport 、则网格管理器信息板上会显示一条提醒消息。

* 在节点页面上查看*已用存储-对象数据*图表时、您现在可以看到网格、站点或存储节点(*节点*>*网格/站点/存储节点_*>*存储*)上复制的对象数据量和经过纠删编码的数据量的估计值。
* 网格管理器菜单选项已重新组织、以便于查找。例如、在*配置*菜单中添加了一个新的*网络设置*子菜单、而*维护*和*支持*菜单中的选项现在按字母顺序列出。


.了解更多信息。
* link:../admin/index.html["管理 StorageGRID"]




== 租户管理器的增强功能

* 租户管理器用户界面的外观和组织经过了全面重新设计、可改善用户体验。
* 新的租户管理器信息板提供每个帐户的概要信息：它提供存储分段详细信息、并显示存储分段或容器、组、用户和平台服务端点(如果已配置)的数量。


.了解更多信息。
* link:../tenant/index.html["使用租户帐户"]




== Prometheus指标导出的客户端证书

现在、您可以上传或生成客户端证书(*配置*>*访问控制*>*客户端证书*)、该证书可用于对StorageGRID Prometheus数据库进行安全的身份验证访问。例如、如果需要使用Grafana从外部监控StorageGRID 、则可以使用客户端证书。

.了解更多信息。
* link:../admin/index.html["管理 StorageGRID"]




== 负载平衡器增强功能

* 现在、在处理站点上的路由请求时、负载平衡器服务将执行负载感知路由：它会考虑同一站点上存储节点的CPU可用性。在某些情况下，有关 CPU 可用性的信息仅限于负载平衡器服务所在的站点。
+

NOTE: 除非站点中至少三分之二的存储节点升级到StorageGRID 11.5并报告CPU统计信息、否则不会启用CPU感知。

* 为了提高安全性、您现在可以为每个负载平衡器端点指定一个绑定模式。通过端点固定、您可以将每个端点的可访问性限制为特定的高可用性组或节点接口。


.了解更多信息。
* link:../admin/index.html["管理 StorageGRID"]




== 对象元数据更改

* *新的实际预留空间指标*：为了帮助您了解和监控每个存储节点上的对象元数据空间使用量、存储节点的"已用存储-对象元数据"图(*节点*>*存储节点_*>*存储节点*>*存储*)上会显示一个新的Prometheus指标。
+
[listing]
----
storagegrid_storage_utilization_metadata_reserved
----
+
"实际预留空间"指标表示StorageGRID 为特定存储节点上的对象元数据预留的空间量。

* *对于具有较大存储节点的安装、增加了元数据空间*：对于包含128 GB或更大RAM的存储节点的StorageGRID 系统、增加了系统范围的元数据预留空间设置、如下所示：
+
** *新安装需要8 TB *：如果要安装新的StorageGRID 11.5系统、并且网格中的每个存储节点都有128 GB或更多RAM、则系统范围的元数据预留空间设置现在将设置为8 TB而不是3 TB。
** 升级需要4 TB *：如果要升级到StorageGRID 11.5、并且任一站点上的每个存储节点都有128 GB或更多RAM、则系统范围的元数据预留空间设置现在将设置为4 TB而不是3 TB。
+
元数据预留空间设置的新值可将这些较大存储节点的允许元数据空间增加到2.64 TB、并确保为未来的硬件和软件版本预留足够的元数据空间。

+
[NOTE]
====
如果存储节点在卷0上具有足够的RAM和空间、则可以在升级后手动将元数据预留空间设置提高到8 TB。在StorageGRID 11.5升级后预留额外的元数据空间将简化未来的硬件和软件升级。

link:increasing-metadata-reserved-space-setting.html["增加元数据预留空间设置"]

====
+

NOTE: 如果您的StorageGRID 系统在任何存储节点上存储(或预期存储)的元数据超过2.64 TB、则在某些情况下、允许的元数据空间可能会增加。如果您的每个存储节点在存储卷0上都有可用空间且RAM超过128 GB、请联系您的NetApp客户代表。如果可能、NetApp将审核您的要求并增加每个存储节点的允许元数据空间。



* *自动清理已删除的元数据*：如果存储节点上存储的20%或更多元数据已准备好删除(因为已删除相应对象)、则StorageGRID 现在可以对该存储节点执行自动数据缩减。只有当系统负载较低时、即有可用的CPU、磁盘空间和内存时、才会运行此后台进程。与先前版本相比、新的数据缩减过程会更快地删除已删除对象的元数据、并有助于为要存储的新对象释放空间。


.了解更多信息。
* link:../admin/index.html["管理 StorageGRID"]




== 对 S3 REST API 支持的更改

* 现在、您可以使用S3 REST API来指定 <<兼容数据的S3对象锁定,S3 对象锁定>> 设置：
+
** 要在启用了S3对象锁定的情况下创建存储分段、请在中使用PUT存储分段请求 `x-amz-bucket-object-lock-enabled` 标题。
** 要确定是否为存储分段启用了S3对象锁定、请使用获取对象锁定配置请求。
** 将对象版本添加到启用了S3对象锁定的存储分段时、请使用以下请求标头指定保留和合法保留设置： `x-amz-object-lock-mode`， `x-amz-object-lock-retain-until-date`，和 `x-amz-object-lock-legal-hold`。


* 现在、您可以使用删除版本控制的存储分段上的多个对象。
* 现在、您可以使用PUT、GET和DELETE分段加密请求来管理现有S3分段的加密。
* 对的字段名称进行了少许更改 `Expiration` 参数。如果生命周期配置适用场景 中的到期规则是特定对象、则此参数会包含在PUT对象、HEAD对象或GET对象请求的响应中。用于指示匹配的到期规则的字段先前已命名 `rule_id`。此字段已重命名为 `rule-id` 以匹配AWS实施。
* 默认情况下、S3获取存储使用情况请求现在会尝试使用全局一致性强的方法检索租户帐户使用的存储及其存储分段。如果无法实现强全局一致性、StorageGRID 将尝试使用强站点一致性检索使用情况信息。
* 。 `Content-MD5` 现在已正确支持请求标头。


.了解更多信息。
* link:../s3/index.html["使用 S3"]




== CloudMirror对象的最大大小增加到5 TB

CloudMirror复制服务可复制到目标存储分段的对象的最大大小已增加到5 TB、这是StorageGRID 支持的最大对象大小。

.了解更多信息。
* link:../s3/index.html["使用 S3"]
* link:../swift/index.html["使用 Swift"]




== 已添加新警报

为StorageGRID 11.5添加了以下新警报：

* 设备 BMC 通信错误
* 检测到设备光纤通道故障
* 设备光纤通道 HBA 端口故障
* 缺少设备 LACP 端口
* Cassandra auto-compactor 错误
* Cassandra 自动数据压缩器指标已过期
* Cassandra compActions 已过载
* 磁盘 I/O 速度非常慢
* Kms CA 证书到期
* Kms 客户端证书到期
* 无法加载 Kms 配置
* Kms 连接错误
* 未找到 Kms 加密密钥名称
* Kms 加密密钥轮换失败
* 未配置公里
* Kms 密钥无法对设备卷进行解密
* Kms 服务器证书到期
* 存储池可用空间不足
* 节点网络接收帧错误
* 服务设备存储连接已降级
* 存储设备存储连接已降级(以前称为设备的存储连接已降级)
* 租户配额使用量高
* 节点意外重新启动


.了解更多信息。
* link:../monitor/index.html["监控和放大；故障排除"]




== SNMP陷阱的TCP支持

现在、您可以选择传输控制协议(Transmission Control Protocol、TCP)作为SNMP陷阱目标的协议。以前、仅支持用户数据报协议(User Datagram Protocol、UDP)协议。

.了解更多信息。
* link:../monitor/index.html["监控和放大；故障排除"]




== 安装和网络连接增强功能

* * MAC地址克隆*：现在、您可以使用MAC地址克隆增强某些环境的安全性。通过MAC地址克隆、您可以对网格网络、管理网络和客户端网络使用专用虚拟NIC。让Docker容器使用主机上专用NIC的MAC地址可以避免使用混杂模式网络配置。在基于Linux的(裸机)节点的节点配置文件中添加了三个新的MAC地址克隆密钥。
* *自动发现DNS和NTP主机路由*：以前、NTP和DNS服务器必须连接到的网络存在一些限制、例如、客户端网络上不能包含所有NTP和DNS服务器。现在、这些限制已被删除。


.了解更多信息。
* link:../rhel/index.html["安装 Red Hat Enterprise Linux 或 CentOS"]
* link:../ubuntu/index.html["安装 Ubuntu 或 Debian"]




== 支持在存储节点扩展后重新平衡纠删编码(Erasure-Coded、EC)数据

EC重新平衡操作步骤 是一个新的命令行脚本、在添加新的存储节点后可能需要使用此脚本。执行操作步骤 时、StorageGRID 会在站点上的现有存储节点和新扩展的存储节点之间重新分布经过擦除编码的片段。


IMPORTANT: 您只能在有限情况下执行EC重新平衡操作步骤。例如、如果无法在扩展中添加建议数量的存储节点、则可以使用EC重新平衡操作步骤 来存储其他经过纠删编码的对象。

.了解更多信息。
* link:../expand/index.html["扩展网格"]




== 新的和经过修订的维护过程

* *站点停用*：现在、您可以从StorageGRID 系统中删除操作站点。已连接站点停用操作步骤 会删除操作站点并保留数据。新的"弃用站点"向导将指导您完成此过程(*维护*>*弃用*>*弃用站点*)。
* *设备节点克隆*：现在、您可以克隆现有设备节点以将此节点升级到新设备型号。例如、您可以将容量较小的设备节点克隆到容量较大的设备。您还可以克隆设备节点以实施新功能、例如KMS加密所需的新*节点加密*设置。
* *能够更改配置密码短语*：您现在可以更改配置密码短语(*配置*>*访问控制*>*网格密码*)。恢复，扩展和维护过程需要密码短语。
* *增强型SSH密码行为*：为增强StorageGRID 设备的安全性、将设备置于维护模式后、SSH密码将不再更改。此外、在将节点升级到StorageGRID 11.5时、系统会生成新的SSH主机证书和主机密钥。
+

NOTE: 如果在升级到StorageGRID 11.5后使用SSH登录到节点、则会收到一条警告、指出主机密钥已更改。此行为是预期行为、您可以安全地批准新密钥。



.了解更多信息。
* link:../maintain/index.html["保持并恢复()"]




== 对StorageGRID 设备进行的更改

* *直接访问适用于存储设备的SANtricity System Manager*：现在、您可以从StorageGRID 设备安装程序和网格管理器访问E系列SANtricity System Manager用户界面。使用这些新方法可以访问SANtricity 系统管理器、而无需使用设备上的管理端口。需要从网格管理器访问SANtricity 系统管理器的用户必须具有新的存储设备管理员权限。
* *节点加密*：在新的KMS加密功能中、StorageGRID 设备安装程序中添加了一个新的*节点加密*设置。如果要使用加密密钥管理来保护设备数据、则必须在设备安装的硬件配置阶段启用此设置。
* * UDP端口连接*：现在、您可以测试StorageGRID 设备与UDP端口的网络连接、例如用于外部NFS或DNS服务器的UDP端口。从StorageGRID 设备安装程序中、选择*配置网络连接*>*端口连接测试(nmap)*。
* *自动化安装和配置*：StorageGRID 设备安装程序(*高级*>*更新设备配置*)添加了一个新的JSON配置上传页面。通过此页面、您可以使用一个文件在大型网格中配置多个设备。此外、还可以使用 `configure-sga.py` Python脚本已进行更新、以与StorageGRID 设备安装程序的功能相匹配。


.了解更多信息。
* link:../sg100-1000/index.html["SG100和AMP；SG1000服务设备"]
* link:../sg6000/index.html["SG6000 存储设备"]
* link:../sg5700/index.html["SG5700 存储设备"]
* link:../sg5600/index.html["SG5600 存储设备"]




== 审核消息的更改

* *自动清理已覆盖对象*：以前、在特定情况下、被覆盖的对象不会从磁盘中删除、从而导致占用更多空间。用户无法访问的这些覆盖对象现在会自动删除以节省存储空间。有关详细信息、请参见LKCU审核消息。
* * S3对象锁定的新审核代码*：在SPUT审核消息中添加了四个新审核代码以包括 <<兼容数据的S3对象锁定,S3 对象锁定>> 请求标题：
+
** LKEN：对象锁定已启用
** LKLH：对象锁定合法保留
** LKmd：对象锁定保留模式
** LKRU：对象锁定保留至日期


* *上次修改时间和先前对象大小的新字段*：现在、您可以跟踪对象被覆盖的时间以及原始对象大小。
+
** MTME (上次修改时间)字段已添加到以下审核消息中：
+
*** SDEL (S3删除)
*** SPUT (S3 PUT)
*** WDEL (Swift delete)
*** WWPUT (Swift PUT)


** CSIZ (先前对象大小)字段已添加到OVWR (对象覆盖)审核消息中。




.了解更多信息。
* link:../audit/index.html["查看审核日志"]




== 新的NMS.requestlog文件

新日志文件、 `/var/local/log/nms.requestlog`在所有管理节点上维护。此文件包含有关从管理API到内部StorageGRID 服务的传出连接的信息。

.了解更多信息。
* link:../monitor/index.html["监控和放大；故障排除"]




== StorageGRID 文档更改

* 为了便于查找网络信息和要求、并明确这些信息也包括 适用场景 StorageGRID 设备节点、网络文档已从基于软件的安装指南(RedHat Enterprise Linux/CentOS、Ubuntu /Debian和VMware)移至新的网络指南。
+
link:../network/index.html["网络准则"]

* 为了便于查找与ILM相关的说明和示例、将用于管理具有信息生命周期管理功能的对象的文档从_Administrator Guides_迁移到了一个新的ILM指南中。
+
link:../ilm/index.html["使用 ILM 管理对象"]

* 新的FabricPool 指南概述了将StorageGRID 配置为NetApp FabricPool 云层的情况、并介绍了为FabricPool 工作负载配置ILM和其他StorageGRID 选项的最佳实践。
+
link:../fabricpool/index.html["为 FabricPool 配置 StorageGRID"]

* 现在、您可以从网格管理器访问多个指导视频。当前视频提供了有关管理警报、自定义警报、ILM规则和ILM策略的说明。

