---
permalink: sg100-1000/reviewing-appliance-network-connections-sg100-and-sg1000.html 
sidebar: sidebar 
keywords: storagegrid, sg100, sg1000, service appliance, services appliance, gateway Node, admin node, network connections, network connection, network, connection, grid, admin, client, bmc, management 
summary: 在安装 StorageGRID 设备之前，您应了解可以将哪些网络连接到此设备。 
---
= 查看设备网络连接
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在安装 StorageGRID 设备之前，您应了解可以将哪些网络连接到此设备。

将 StorageGRID 设备部署为 StorageGRID 系统中的节点时，您可以将其连接到以下网络：

* * 适用于 StorageGRID 的网格网络 * ：网格网络用于所有内部 StorageGRID 流量。它可以在网格中的所有节点之间以及所有站点和子网之间建立连接。网格网络为必填项。
* * 适用于 StorageGRID 的管理网络 * ：管理网络是一个用于系统管理和维护的封闭网络。管理网络通常是一个专用网络，不需要在站点之间进行路由。管理网络是可选的。
* * 适用于 StorageGRID 的客户端网络： * 客户端网络是一种开放网络，用于访问包括 S3 和 Swift 在内的客户端应用程序。客户端网络可提供对网格的客户端协议访问，从而可以隔离和保护网格网络。您可以配置客户端网络，以便仅使用您选择打开的端口通过此网络访问设备。客户端网络是可选的。
* *用于服务设备的BMC管理网络：*通过此网络、您可以访问SG100和SG1000中的基板管理控制器、这些设备允许您监控和管理设备中的硬件组件。此管理网络可以与 StorageGRID 的管理网络相同，也可以是一个独立的管理网络。


.相关信息
link:gathering-installation-information-sg100-and-sg1000.html["收集安装信息(SG100和SG1000)"]

link:cabling-appliance-sg100-and-sg1000.html["为设备SG100和SG1000布线)"]

link:../network/index.html["网络准则"]

link:../primer/index.html["网格入门"]
