---
permalink: network/networking-and-ports-for-platform-services-and-cloud-storage-pools.html 
sidebar: sidebar 
keywords:  
summary: 如果您计划使用 StorageGRID 平台服务或云存储池，则必须配置网格网络和防火墙以确保可以访问目标端点。平台服务包括提供搜索集成、事件通知和CloudMirror复制的外部服务。 
---
= 用于平台服务和云存储池的网络和端口
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您计划使用 StorageGRID 平台服务或云存储池，则必须配置网格网络和防火墙以确保可以访问目标端点。平台服务包括提供搜索集成、事件通知和CloudMirror复制的外部服务。

平台服务需要从托管 StorageGRID ADA 服务的存储节点访问外部服务端点。提供访问权限的示例包括：

* 在具有 ADE 服务的存储节点上，使用路由到目标端点的 AESL 条目配置唯一管理网络。
* 依靠客户端网络提供的默认路由。在此示例中、可以使用不可信客户端网络功能限制入站连接。


云存储池还需要从存储节点访问所使用的外部服务提供的端点，例如 Amazon S3 Glacier 或 Microsoft Azure Blob 存储。

默认情况下，平台服务和云存储池通信使用以下端口：

* * 80*：对于以开头的端点URI `http`
* * 443：对于以开头的端点URI `https`


创建或编辑端点时，可以指定其他端口。

如果您使用的是非透明代理服务器、则还必须配置代理设置、以允许将消息发送到外部端点、例如Internet上的端点。请参见管理StorageGRID 以了解如何配置代理设置。

有关不可信客户端网络的详细信息、请参见有关管理StorageGRID 的说明。有关平台服务的详细信息、请参见有关使用租户帐户的说明。有关云存储池的详细信息、请参见有关通过信息生命周期管理来管理对象的说明。

.相关信息
link:network-port-reference.html["网络端口参考"]

link:../primer/index.html["网格入门"]

link:../admin/index.html["管理 StorageGRID"]

link:../tenant/index.html["使用租户帐户"]

link:../ilm/index.html["使用 ILM 管理对象"]
