---
permalink: vmware/downloading-and-extracting-storagegrid-installation-files.html 
sidebar: sidebar 
keywords: storagegrid, vmware, download installation files, downloading installation files 
summary: 您必须下载 StorageGRID 安装归档并提取文件。 
---
= 下载并提取StorageGRID 安装文件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您必须下载StorageGRID 安装归档并提取文件。

.步骤
. 转到 StorageGRID 的 "NetApp 下载 " 页面。
+
https://["NetApp 下载： StorageGRID"^]

. 选择用于下载最新版本的按钮，或者从下拉菜单中选择其他版本并选择 * 执行 * 。
. 使用您的 NetApp 帐户的用户名和密码登录。
. 如果显示 Caution/MustRead 语句，请阅读该语句并选中复选框。
+
安装 StorageGRID 版本后，您必须应用任何所需的修补程序。有关详细信息、请参见恢复和维护说明中的修补程序操作步骤。

. 阅读最终用户许可协议，选中复选框，然后选择 * 接受并继续 * 。
. 在*安装StorageGRID *列中、选择相应的软件。
+
下载 `.tgz` 或 `.zip` 适用于您的平台的归档文件。

+
** `StorageGRID-Webscale-version-VMware-uniqueID.zip`
** `StorageGRID-Webscale-version-VMware-uniqueID.tgz`





NOTE: 使用 `.zip` 如果您在服务笔记本电脑上运行Windows、则将文件保存。

. 保存并提取归档文件。
. 从以下列表中选择所需的文件。
+
所需的文件取决于您规划的网格拓扑以及如何部署 StorageGRID 系统。




NOTE: 表中列出的路径与提取的安装归档所安装的顶级目录相对。

[cols="1a,1a"]
|===
| 路径和文件名 | Description 


| ./vSphere/README  a| 
一个文本文件，用于描述 StorageGRID 下载文件中包含的所有文件。



| ./vSphere/NLF000000.txt  a| 
一种免费许可证，不提供产品的任何支持授权。



| ./vsphere/netapp-sg-version-sha.vmdk  a| 
用作创建网格节点虚拟机的模板的虚拟机磁盘文件。



| ./vSphere/vsphere-primary-admin.OVF ./vsphere/vsphere-primary-admin.mf  a| 
开放式虚拟化格式模板文件 (`.ovf`)和清单文件 (`.mf`)以部署主管理节点。



| ./vSphere/vsphere-non-primary-admin.OVF ./vsphere/vsphere-non-primary-admin.mf  a| 
模板文件 (`.ovf`)和清单文件 (`.mf`)以部署非主管理节点。



| ./vSphere/vsphere-archive.OVF ./vsphere/vsphere-archive.mf  a| 
模板文件 (`.ovf`)和清单文件 (`.mf`)以部署归档节点。



| ./vSphere/vsphere-gateway.OVF ./vsphere/vsphere-gateway.mf  a| 
模板文件 (`.ovf`)和清单文件 (`.mf`)以部署网关节点。



| ./vSphere/vsphere-storage.OVF ./vsphere/vsphere-storage.mf  a| 
模板文件 (`.ovf`)和清单文件 (`.mf`)以部署基于虚拟机的存储节点。



| 部署脚本工具 | Description 


| ./vSphere/deploy-vsphere-ovftool.sh  a| 
Bash shell 脚本，用于自动部署虚拟网格节点。



| ./vSphere/deploy-vsphere-ovftool-sample.ini  a| 
用于的示例配置文件 `deploy-vsphere-ovftool.sh` 脚本。



| ./vSphere/configure-storagegrid.py  a| 
一种用于自动配置 StorageGRID 系统的 Python 脚本。



| ./vSphere/configure-sga.py  a| 
一种用于自动配置 StorageGRID 设备的 Python 脚本。



| ./vSphere/storagegrid-ssoauth.py  a| 
一个示例 Python 脚本，启用单点登录后，您可以使用该脚本登录到网格管理 API 。



| ./vsphere/configure-storaggrid.sample.json  a| 
用于的示例配置文件 `configure-storagegrid.py` 脚本。



| ./vsphere/configure-storaggrid.blank.json  a| 
用于的空白配置文件 `configure-storagegrid.py` 脚本。

|===
.相关信息
link:../maintain/index.html["保持并恢复()"]
