---
permalink: rhel/configuring-host-network.html 
sidebar: sidebar 
keywords:  
summary: 在主机上完成 Linux 安装后，您可能需要执行一些额外的配置，以便在每个主机上准备一组适合映射到稍后要部署的 StorageGRID 节点的网络接口。 
---
= 配置主机网络
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在主机上完成 Linux 安装后，您可能需要执行一些额外的配置，以便在每个主机上准备一组适合映射到稍后要部署的 StorageGRID 节点的网络接口。

.您需要的内容
* 您已查看StorageGRID 网络连接准则。
+
link:../network/index.html["网络准则"]

* 您已查看有关节点容器迁移要求的信息。
+
link:node-container-migration-requirements.html["节点容器迁移要求"]

* 如果使用的是虚拟主机、则在配置主机网络之前、您已阅读有关MAC地址克隆的注意事项和建议。
+
link:considerations-and-recommendations-for-mac-address-cloning.html["MAC 地址克隆的注意事项和建议"]




NOTE: 如果要使用 VM 作为主机，则应选择 VMXNET 3 作为虚拟网络适配器。VMware E1000 网络适配器已导致在某些 Linux 版本上部署 StorageGRID 容器时出现连接问题。

.关于此任务
网格节点必须能够访问网格网络，还可以访问管理网络和客户端网络。您可以通过创建映射来提供此访问权限，此映射会将主机的物理接口与每个网格节点的虚拟接口相关联。创建主机接口时，请使用友好名称以方便在所有主机之间进行部署，并启用迁移。

同一接口可以在主机与一个或多个节点之间共享。例如，您可以使用相同的接口进行主机访问和节点管理网络访问，以便于维护主机和节点。尽管主机和各个节点之间可以共享同一接口，但所有接口都必须具有不同的 IP 地址。不能在节点之间或主机与任何节点之间共享 IP 地址。

您可以使用相同的主机网络接口为主机上的所有 StorageGRID 节点提供网格网络接口；可以为每个节点使用不同的主机网络接口；也可以在这两者之间执行操作。但是，通常不会提供与单个节点的网格和管理网络接口相同的主机网络接口，也不会提供与一个节点的网格网络接口和另一个节点的客户端网络接口相同的主机网络接口。

您可以通过多种方式完成此任务。例如，如果您的主机是虚拟机，而您要为每个主机部署一个或两个 StorageGRID 节点，则只需在虚拟机管理程序中创建正确数量的网络接口并使用一对一映射即可。如果要在裸机主机上部署多个节点以供生产使用，则可以利用 Linux 网络堆栈对 VLAN 和 LACP 的支持来实现容错和带宽共享。以下各节详细介绍了这两个示例的方法。您无需使用上述任一示例；您可以使用任何满足您需求的方法。


NOTE: 请勿直接使用绑定或网桥设备作为容器网络接口。这样做可能会阻止内核问题描述 在容器命名空间中对绑定和网桥设备使用 MACVLAN 导致节点启动。请改用非绑定设备，例如 VLAN 或虚拟以太网（ Veth ）对。在节点配置文件中指定此设备作为网络接口。

.相关信息
link:../network/index.html["网络准则"]

link:node-container-migration-requirements.html["节点容器迁移要求"]

link:creating-node-configuration-files.html["正在创建节点配置文件"]
