---
permalink: admin/configuring-custom-server-certificate-for-storage-node-or-clb.html 
sidebar: sidebar 
keywords:  
summary: 您可以替换用于通过S3或Swift客户端连接到存储节点或网关节点上的CLB服务的服务器证书。替换的自定义服务器证书特定于您的组织。 
---
= 配置自定义服务器证书以连接到存储节点或CLB服务
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以替换用于通过S3或Swift客户端连接到存储节点或网关节点上的CLB服务(已弃用)的服务器证书。替换的自定义服务器证书特定于您的组织。

.关于此任务
默认情况下，每个存储节点都会获得一个由网格 CA 签名的 X.509 服务器证书。这些 CA 签名的证书可以替换为一个通用的自定义服务器证书和相应的专用密钥。

所有存储节点都使用一个自定义服务器证书，因此，如果客户端在连接到存储端点时需要验证主机名，则必须将此证书指定为通配符或多域证书。定义自定义证书，使其与网格中的所有存储节点匹配。

在服务器上完成配置后、用户可能还需要在用于访问系统的S3或Swift API客户端中安装根CA证书、具体取决于所使用的根证书颁发机构(CA)。


NOTE: 为了确保操作不会因服务器证书失败而中断、在根服务器证书即将过期时、系统会触发*存储API端点服务器证书到期*警报和原有的存储API服务端点证书到期(SCEP)警报。根据需要、您可以选择*支持***工具***网格拓扑*来查看当前服务证书到期前的天数。然后、选择*主管理节点_*** CMN***资源*。

只有当客户端在网关节点上使用已弃用的CLB服务连接到StorageGRID 或直接连接到存储节点时、才会使用自定义证书。在管理节点或网关节点上使用负载平衡器服务连接到StorageGRID 的S3或Swift客户端使用为负载平衡器端点配置的证书。


NOTE: 负载平衡器端点的*负载平衡器端点证书到期*警报将触发、该端点不久将过期。

.步骤
. 选择*配置*>*网络设置*>*服务器证书*。
. 在对象存储API服务端点服务器证书部分中、单击*安装自定义证书*。
. 上传所需的服务器证书文件：
+
** *服务器证书*：自定义服务器证书文件 (`.crt`）。
** *服务器证书专用密钥*：自定义服务器证书专用密钥文件 (`.key`）。
+

NOTE: EC 专用密钥必须大于或等于 224 位。RSA 私钥必须大于或等于 2048 位。

** * CA Bundle*：一个文件、其中包含来自每个中间颁发证书颁发机构(CA)的证书。此文件应包含 PEM 编码的每个 CA 证书文件，并按证书链顺序串联。


. 单击 * 保存 * 。
+
自定义服务器证书用于所有后续新的API客户端连接。

+
选择一个选项卡以显示有关已上传的默认StorageGRID 服务器证书或CA签名证书的详细信息。

+

NOTE: 上传新证书后、请留出最多一天的时间来清除任何相关证书到期警报(或旧警报)。

. 刷新页面以确保 Web 浏览器已更新。


.相关信息
link:../s3/index.html["使用 S3"]

link:../swift/index.html["使用 Swift"]

link:configuring-s3-api-endpoint-domain-names.html["配置S3 API端点域名"]
