---
permalink: admin/configuring-custom-server-certificate-for-grid-manager-tenant-manager.html 
sidebar: sidebar 
keywords:  
summary: 您可以将默认 StorageGRID 服务器证书替换为一个自定义服务器证书，该证书允许用户访问网格管理器和租户管理器，而不会遇到安全警告。 
---
= 为网格管理器和租户管理器配置自定义服务器证书
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以将默认 StorageGRID 服务器证书替换为一个自定义服务器证书，该证书允许用户访问网格管理器和租户管理器，而不会遇到安全警告。

.关于此任务
默认情况下，每个管理节点都会获得一个由网格 CA 签名的证书。这些 CA 签名的证书可以替换为一个通用的自定义服务器证书和相应的专用密钥。

由于所有管理节点都使用一个自定义服务器证书、因此、如果客户端在连接到网格管理器和租户管理器时需要验证主机名、则必须将此证书指定为通配符或多域证书。定义自定义证书，使其与网格中的所有管理节点匹配。

您需要在服务器上完成配置、根据所使用的根证书颁发机构(CA)、用户可能还需要在用于访问网格管理器和租户管理器的Web浏览器中安装根CA证书。


NOTE: 为了确保操作不会因服务器证书失败而中断、当此服务器证书即将过期时、系统会触发*管理接口的服务器证书到期*警报和原有的管理接口证书到期(Management Interface Certificate Expiration、MCEP)警报。根据需要、您可以选择*支持*>*工具*>*网格拓扑*来查看当前服务证书到期前的天数。然后、选择*主管理节点_*>*。CMN*>*资源*。

[NOTE]
====
如果您要使用域名而非 IP 地址访问网格管理器或租户管理器，则在发生以下任一情况时，浏览器将显示证书错误，并且无法绕过此错误：

* 您的自定义管理接口服务器证书将过期。
* 您可以从自定义管理接口服务器证书还原到默认服务器证书。


====
.步骤
. 选择*配置*>*网络设置*>*服务器证书*。
. 在管理接口服务器证书部分中、单击*安装自定义证书*。
. 上传所需的服务器证书文件：
+
** *服务器证书*：自定义服务器证书文件 (`.crt`）。
** *服务器证书专用密钥*：自定义服务器证书专用密钥文件 (`.key`）。
+

NOTE: EC 专用密钥必须大于或等于 224 位。RSA 私钥必须大于或等于 2048 位。

** * CA Bundle*：一个文件、其中包含来自每个中间颁发证书颁发机构(CA)的证书。此文件应包含 PEM 编码的每个 CA 证书文件，并按证书链顺序串联。


. 单击 * 保存 * 。
+
自定义服务器证书将用于所有后续的新客户端连接。

+
选择一个选项卡以显示有关已上传的默认StorageGRID 服务器证书或CA签名证书的详细信息。

+

NOTE: 上传新证书后、请留出最多一天的时间来清除任何相关证书到期警报(或旧警报)。

. 刷新页面以确保 Web 浏览器已更新。

