---
permalink: admin/configuring-storagegrid-certificates-for-fabricpool.html 
sidebar: sidebar 
keywords:  
summary: 对于执行严格主机名验证且不支持禁用严格主机名验证的 S3 客户端，例如使用 FabricPool 的 ONTAP 客户端，您可以在配置负载平衡器端点时生成或上传服务器证书。 
---
= 为FabricPool 配置StorageGRID 证书
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
对于执行严格主机名验证且不支持禁用严格主机名验证的 S3 客户端，例如使用 FabricPool 的 ONTAP 客户端，您可以在配置负载平衡器端点时生成或上传服务器证书。

.您需要的内容
* 您必须具有特定的访问权限。
* 您必须使用支持的浏览器登录到网格管理器。


.关于此任务
创建负载平衡器端点时、您可以生成自签名服务器证书或上传由已知证书颁发机构(CA)签名的证书。在生产环境中，您应使用由已知 CA 签名的证书。由 CA 签名的证书可以无中断地轮换。它们也更安全，因为它们可以更好地防止中间人攻击。

以下步骤为使用 FabricPool 的 S3 客户端提供了一般准则。有关更多详细信息和过程、请参见有关为FabricPool 配置StorageGRID 的说明。


NOTE: 网关节点上的单独连接负载平衡器（ CLB ）服务已弃用，不再建议用于 FabricPool 。

.步骤
. （可选）配置一个高可用性（ High Availability ， HA ）组以供 FabricPool 使用。
. 创建 S3 负载平衡器端点以供 FabricPool 使用。
+
创建HTTPS负载平衡器端点时、系统会提示您上传服务器证书、证书专用密钥和CA捆绑包。

. 在 ONTAP 中将 StorageGRID 附加为云层。
+
指定负载平衡器端点端口以及上载的 CA 证书中使用的完全限定域名。然后，提供 CA 证书。

+

NOTE: 如果中间 CA 颁发了 StorageGRID 证书，则必须提供中间 CA 证书。如果 StorageGRID 证书是直接由根 CA 颁发的，则必须提供根 CA 证书。



.相关信息
link:../fabricpool/index.html["为 FabricPool 配置 StorageGRID"]
