---
permalink: admin/creating-tenant-account-if-sso-is-enabled.html 
sidebar: sidebar 
keywords:  
summary: '创建租户帐户时，您可以指定名称，客户端协议以及存储配额（可选）。如果为StorageGRID 启用了单点登录\(SSO\)、则还可以指定具有root访问权限的联合组来配置租户帐户。' 
---
= 如果启用了SSO、则创建租户帐户
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
创建租户帐户时，您可以指定名称，客户端协议以及存储配额（可选）。如果为StorageGRID 启用了单点登录(SSO)、则还可以指定具有root访问权限的联合组来配置租户帐户。

.步骤
. 在*显示名称*文本框中、输入此租户帐户的显示名称。
+
显示名称不必唯一。创建租户帐户时、它会收到一个唯一的数字帐户ID。

. 选择此租户帐户要使用的客户端协议、可以是* S3或* Swift*。
. 对于S3租户帐户、请保持选中*允许平台服务*复选框、除非您不希望此租户对S3分段使用平台服务。
+
如果启用了平台服务，则租户可以使用 CloudMirror 复制等功能来访问外部服务。您可能需要禁用这些功能来限制租户使用的网络带宽或其他资源量。请 `M" 管理平台服务 " 。`

. 在*存储配额*文本框中、也可以输入要为此租户对象提供的最大GB、TB或PB数。然后、从下拉列表中选择单位。
+
如果希望此租户拥有无限配额、请将此字段留空。

+

NOTE: 租户的存储配额表示逻辑容量（对象大小），而不是物理容量（磁盘大小）。ILM副本和纠删编码不会影响所使用的配额量。如果超过配额、租户帐户将无法创建新对象。

+

NOTE: 要监控每个租户帐户的存储使用情况、请选择*使用情况*。租户帐户还可以通过租户管理器中的信息板或租户管理API监控自己的存储使用情况。请注意、如果节点与网格中的其他节点隔离、则租户的存储使用量值可能会过时。恢复网络连接后，总数将更新。

. 请注意、未选中和禁用*使用自己的身份源*复选框。
+
由于启用了SSO、租户必须使用为网格管理器配置的身份源。没有本地用户可以登录。

. 在*根访问组*字段中、从网格管理器中选择一个现有联合组、以便为租户提供初始根访问权限。
+

NOTE: 如果您拥有足够的权限、则在单击此字段时会列出网格管理器中的现有联合组。否则，请输入组的唯一名称。

. 单击 * 保存 * 。
+
此时将创建租户帐户。此时将显示租户帐户页面、其中包含新租户对应的行。

. 如果您是root访问组中的用户、也可以单击新租户的*登录*链接以立即访问租户管理器、您可以在其中配置租户。否则、请将*登录*链接的URL提供给租户帐户的管理员。(租户的URL是任何管理节点的完全限定域名或IP地址、后跟 `/?accountId=_20-digit-account-id_`）
+

NOTE: 如果单击*登录*、则会显示访问被拒绝消息、但您不属于租户帐户的根访问组。



.相关信息
link:configuring-sso.html["配置单点登录"]

link:managing-platform-services-for-s3-tenant-accounts.html["管理S3租户帐户的平台服务"]

link:../tenant/index.html["使用租户帐户"]
