---
permalink: admin/managing-local-users.html 
sidebar: sidebar 
keywords:  
summary:  
---
= 管理本地用户
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以创建本地用户并将其分配给本地管理组、以确定这些用户可以访问哪些网格管理器功能。

网格管理器包括一个名为"`root"的预定义本地用户。`虽然您可以添加和删除本地用户、但不能删除root用户。


NOTE: 如果已启用单点登录(SSO)、则本地用户无法登录到StorageGRID。

* 您必须使用支持的浏览器登录到网格管理器。
* 您必须具有特定的访问权限。




== 创建本地用户

如果已创建本地管理组、则可以创建一个或多个本地用户、并将每个用户分配给一个或多个组。组的权限控制用户可以访问的网格管理器功能。

.关于此任务
您只能创建本地用户、并且只能将这些用户分配给本地管理组。联合用户和联合组使用外部身份源进行管理。

.步骤
. 选择*配置*>*访问控制*>*管理用户*。
. 单击 * 创建 * 。
. 输入用户的显示名称、唯一名称和密码。
. 将用户分配给一个或多个控制访问权限的组。
+
组名称列表是从组表生成的。

. 单击 * 保存 * 。


.相关信息
link:managing-admin-groups.html["管理管理组"]



== 修改本地用户的帐户

您可以修改本地管理员用户的帐户以更新用户的显示名称或组成员资格。您还可以临时阻止用户访问系统。

.关于此任务
您只能编辑本地用户。联合用户详细信息会自动与外部身份源同步。

.步骤
. 选择*配置*>*访问控制*>*管理用户*。
. 选择要编辑的用户。
+
如果您的系统包含20个以上的项目、则可以指定一次在每个页面上显示的行数。然后、您可以使用浏览器的"查找"功能在当前显示的行中搜索特定项。

. 单击 * 编辑 * 。
. 或者、也可以更改名称或组成员资格。
. 或者、要防止用户临时访问系统、请选中*拒绝访问*。
. 单击 * 保存 * 。
+
新设置将在用户下次注销后重新登录到网格管理器时应用。





== 删除本地用户的帐户

您可以删除不再需要访问网格管理器的本地用户帐户。

.步骤
. 选择*配置*>*访问控制*>*管理用户*。
. 选择要删除的本地用户。
+

NOTE: 您不能删除预定义的root本地用户。

+
如果您的系统包含20个以上的项目、则可以指定一次在每个页面上显示的行数。然后、您可以使用浏览器的"查找"功能在当前显示的行中搜索特定项。

. 单击 * 删除 * 。
. 单击 * 确定 * 。




== 更改本地用户的密码

本地用户可以使用网格管理器横幅中的 * 更改密码 * 选项更改自己的密码。此外、有权访问Admin Users页面的用户还可以更改其他本地用户的密码。

.关于此任务
您只能更改本地用户的密码。联合用户必须在外部身份源中更改自己的密码。

.步骤
. 选择*配置*>*访问控制*>*管理用户*。
. 从用户页面中、选择用户。
+
如果您的系统包含20个以上的项目、则可以指定一次在每个页面上显示的行数。然后、您可以使用浏览器的"查找"功能在当前显示的行中搜索特定项。

. 单击*更改密码*。
. 输入并确认密码、然后单击*保存*。

