---
permalink: s3/head-object.html 
sidebar: sidebar 
keywords:  
summary: 您可以使用 S3 head Object 请求从对象检索元数据，而无需返回对象本身。 
---
= HEAD 对象
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用 S3 head Object 请求从对象检索元数据，而无需返回对象本身。如果对象存储在云存储池中，则可以使用 head 对象确定对象的过渡状态。



== 使用客户提供的加密密钥（ SSI-C ）进行服务器端加密的请求标头

如果对象使用您提供的唯一密钥进行加密，请使用所有这三个标头。

* `x-amz-server-side-encryption-customer-algorithm`：指定 `AES256`。
* `x-amz-server-side-encryption-customer-key`：指定对象的加密密钥。
* `x-amz-server-side-encryption-customer-key-MD5`：指定对象加密密钥的MD5摘要。



IMPORTANT: 您提供的加密密钥永远不会存储。如果丢失加密密钥，则会丢失相应的对象。在使用客户提供的密钥保护对象数据之前、请查看"`使用服务器端加密中的注意事项。`



== 用户元数据中的 UTF-8 字符

StorageGRID 不会解析或解释用户定义的元数据中的转义 UTF-8 字符。对于用户定义的元数据中具有转义UTF-8字符的对象、如果对该对象发出机头请求、则不会返回 `x-amz-missing-meta` 如果密钥名称或值包含不可打印的字符、则为标题。



== 请求标头不受支持

不支持以下请求标头、并返回 `XNotImplemented`：

* `x-amz-website-redirect-location`




== Cloud Storage Pool 对象的响应标头

如果对象存储在云存储池中（请参见有关通过信息生命周期管理来管理对象的说明），则返回以下响应标头：

* `x-amz-storage-class: GLACIER`
* `x-amz-restore`


响应标头提供了有关对象移动到云存储池，可选择过渡到不可检索状态并已还原时的状态的信息。

|===
| 对象的状态 | 对 head 对象的响应 


 a| 
对象已载入 StorageGRID 但尚未通过 ILM 进行评估，或者存储在传统存储池中的对象或使用纠删编码
 a| 
`200 OK` (不返回任何特殊的响应标头。)



 a| 
云存储池中的对象，但尚未过渡到无法检索的状态
 a| 
`200 OK`

`x-amz-storage-class: GLACIER`

`x-amz-restore: ongoing-request="false", expiry-date="Sat, 23 July 20 2030 00:00:00 GMT"`

在将对象过渡到无法检索的状态之前、为提供的值 `expiry-date` 设置为未来的某个远程时间。确切的过渡时间不受 StorageGRID 系统控制。



 a| 
对象已过渡到不可检索状态，但网格上至少也存在一个副本
 a| 
`200 OK`

`x-amz-storage-class: GLACIER`

`x-amz-restore: ongoing-request="false", expiry-date="Sat, 23 July 20 2030 00:00:00 GMT"`

的值 `expiry-date` 设置为未来的某个远程时间。

* 注意 * ：如果网格上的副本不可用（例如，存储节点已关闭），则必须先对后对象还原请求进行问题描述 处理，以便从云存储池还原此副本，然后才能成功检索此对象。



 a| 
对象已过渡到无法检索的状态，网格上不存在任何副本
 a| 
`200 OK`

`x-amz-storage-class: GLACIER`



 a| 
正在从不可检索状态还原的对象
 a| 
`200 OK`

`x-amz-storage-class: GLACIER`

`x-amz-restore: ongoing-request="true"`



 a| 
对象已完全还原到云存储池
 a| 
`200 OK`

`x-amz-storage-class: GLACIER`

`x-amz-restore: ongoing-request="false", expiry-date="Sat, 23 July 20 2018 00:00:00 GMT"`

。 `expiry-date` 指示何时将云存储池中的对象返回到无法检索的状态。

|===


== 云存储池中的多部分或分段对象

如果您上传的是多部分对象或 StorageGRID 将一个大型对象拆分为多个区块，则 StorageGRID 会通过取样该对象的部分或区块来确定该对象是否在云存储池中可用。在某些情况下、可能会错误地返回HEAD对象请求 `x-amz-restore: ongoing-request="false"` 对象的某些部分已过渡到无法检索的状态、或者对象的某些部分尚未还原。



== 版本控制

如果为 `versionId` 未指定子资源、此操作将提取受版本控制的存储分段中的对象的最新版本。如果对象的当前版本为删除标记、则会使用返回"`not found`"状态 `x-amz-delete-marker` 响应标头设置为 `true`。

.相关信息
link:s3-rest-api-supported-operations-and-limitations.html["使用服务器端加密"]

link:../ilm/index.html["使用 ILM 管理对象"]

link:post-object-restore.html["后对象还原"]

link:s3-operations-tracked-in-audit-logs.html["审核日志中跟踪的 S3 操作"]
