---
permalink: monitor/generating-text-reports.html 
sidebar: sidebar 
keywords: reports, text 
summary: 文本报告以文本形式显示 NMS 服务已处理的属性数据值。您可以报告数据中心站点，网格节点，组件或服务。 
---
= 正在生成文本报告
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
文本报告以文本形式显示 NMS 服务已处理的属性数据值。您可以报告数据中心站点，网格节点，组件或服务。

.您需要的内容
* 您必须使用支持的浏览器登录到网格管理器。
* 您必须具有特定的访问权限。


.关于此任务
对于预期会持续更改的属性数据， NMS 服务（在源上）会定期对这些属性数据进行采样。对于不经常更改的属性数据（例如，基于状态或状态更改等事件的数据），当属性值发生更改时，会将该属性值发送到 NMS 服务。

显示的报告类型取决于配置的时间段。默认情况下，系统会为超过一周的时间段生成聚合文本报告。

灰色文本表示服务在取样期间被管理员关闭。蓝色文本表示服务处于未知状态。

.步骤
. 选择*支持*>*工具*>*网格拓扑*。
. 选择 *_GRID NODE_* > * 组件或 service_* > * 报告 * > * 文本 * 。
. 从 * 属性 * 下拉列表中选择要报告的属性。
. 从 * 每页结果 * 下拉列表中选择每页结果数。
. 要将值舍入为最多三位小数（例如，对于以百分比形式报告的属性），请取消选中 * 原始数据 * 复选框。
. 从 * 快速查询 * 下拉列表中选择要报告的时间段。
+
选择自定义查询选项以选择特定的时间范围。

+
此报告将在片刻后显示。请留出几分钟时间，以表格形式列出较长的时间范围。

. 如果选择了自定义查询，则需要输入 * 开始日期 * 和 * 结束日期 * 来自定义要报告的时间段。
+
使用格式 `YYYY/MM/DDHH:MM:SS` 在本地时间。要与格式匹配，必须使用前导零。例如， 2017/4/6 7 ： 30 ： 00 验证失败。正确格式为 2017 年 4 月 06 日 07 ： 30 ： 00 。

. 单击 * 更新 * 。
+
稍后将生成一个文本报告。请留出几分钟时间，以表格形式列出较长的时间范围。根据为查询设置的时间长度，将显示原始文本报告或聚合文本报告。

. 如果要打印报告、请右键单击并选择*打印*、然后修改任何必要的打印机设置、然后单击*打印*。

