---
permalink: monitor/logs-for-third-party-software.html 
sidebar: sidebar 
keywords: troubleshooting, logs 
summary: 您可以使用第三方软件日志对问题进行故障排除。 
---
= 第三方软件的日志
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用第三方软件日志对问题进行故障排除。

|===
| 类别 | 文件名 | 注释： | 在上找到 


 a| 
apache2日志
 a| 
`/var/local/log/apache2/access.log /var/local/log/apache2/error.log`

`/var/local/log/apache2/other_vhosts_access.log`
 a| 
apache2的日志文件。
 a| 
管理节点



 a| 
归档
 a| 
`/var/local/log/dsierror.log`
 a| 
TSM 客户端 API 的错误信息。
 a| 
归档节点



 a| 
MySQL
 a| 
/var/local/log/mysql.err`

`/var/local/log/mysql.err /var/local/log/mysql-slow.log`
 a| 
MySQL 生成的日志文件。

文件mysql.err可捕获数据库错误和事件、例如启动和关闭。

文件mysql-slow.log (查询日志速度较慢)可捕获执行时间超过10秒的SQL语句。
 a| 
管理节点



 a| 
操作系统
 a| 
`/var/local/log/messages`
 a| 
此目录包含操作系统的日志文件。这些日志中包含的错误也会显示在网格管理器中。选择*支持*>*工具*>*网格拓扑*。然后选择 * 拓扑 * > * 站点 _* > * 节点 _* > * SSM* > * 事件 * 。
 a| 
所有节点



 a| 
NTP
 a| 
`/var/local/log/ntp.log`

`/var/lib/ntp/var/log/ntpstats/`
 a| 
。 `/var/local/log/ntp.log` 包含NTP错误消息的日志文件。

。 `/var/lib/ntp/var/log/ntpstats/` 目录包含NTP时间统计信息。

`loopstats` 记录环路筛选器统计信息。

`peerstats` 记录对等统计信息。
 a| 
所有节点



 a| 
SAMBA
 a| 
`/var/local/log/samba/`
 a| 
Samba 日志目录包含每个 Samba 进程（ SMB ， nmb 和 winbind ）以及每个客户端主机名 /IP 的日志文件。
 a| 
已配置管理节点，用于通过 CIFS 导出审核共享

|===