---
permalink: maintain/recovering-from-primary-admin-node-failures.html 
sidebar: sidebar 
keywords: storagegrid, recover, primary admin node failure 
summary: 要从主管理节点故障中恢复，您必须完成一组特定的任务。主管理节点托管网格的配置管理节点（ CMN\ ）服务。 
---
= 从主管理节点故障中恢复
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
要从主管理节点故障中恢复，您必须完成一组特定的任务。主管理节点托管网格的配置管理节点（ CMN ）服务。

.关于此任务
应立即更换发生故障的主管理节点。主管理节点上的配置管理节点（ CMN ）服务负责为网格发出对象标识符块。这些标识符将在载入对象时分配给对象。除非具有可用标识符，否则无法载入新对象。由于网格中缓存了大约一个月的标识符，因此在 CMN 不可用时，对象载入可以继续。但是，在缓存的标识符用尽后，无法添加任何新对象。


IMPORTANT: 您必须在大约一个月内修复或更换发生故障的主管理节点，否则网格可能无法载入新对象。确切的时间段取决于对象载入率：如果您需要更准确地评估网格的时间范围，请联系技术支持。

.步骤
* link:copying-audit-logs-from-failed-primary-admin-node.html["从发生故障的主管理节点复制审核日志"]
* link:replacing-primary-admin-node.html["更换主管理节点"]
* link:configuring-replacement-primary-admin-node.html["配置替代主管理节点"]
* link:restoring-audit-log-on-recovered-primary-admin-node.html["在已恢复的主管理节点上还原审核日志"]
* link:resetting-preferred-sender-on-recovered-primary-admin-node.html["在已恢复的主管理节点上重置首选发送器"]
* link:restoring-admin-node-database-primary-admin-node.html["恢复主管理节点时还原管理节点数据库"]
* link:restoring-prometheus-metrics-primary-admin-node.html["恢复主管理节点时还原Prometheus指标"]

