---
permalink: maintain/restoring-and-validating-grid-nodes.html 
sidebar: sidebar 
keywords: storagegrid, recover, restore grid node, restore node, validate grid node, validate node 
summary: 您必须还原任何出现故障的网格节点的网格配置文件，然后验证网格配置文件并解决任何错误。 
---
= 还原和验证网格节点
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您必须还原任何出现故障的网格节点的网格配置文件，然后验证网格配置文件并解决任何错误。

.关于此任务
您可以导入主机上应存在的任何网格节点、只要该节点存在即可 `/var/local` 卷未因上一主机故障而丢失。例如、 `/var/local` 如果您对StorageGRID 系统数据卷使用共享存储、则卷可能仍存在、如适用于Linux操作系统的StorageGRID 安装说明中所述。导入节点会将其节点配置文件还原到主机。

如果无法导入缺少的节点，则必须重新创建其网格配置文件。

然后，您必须验证网格配置文件，并解决可能发生的任何网络或存储问题，然后再继续重新启动 StorageGRID 。重新创建节点的配置文件时，必须为要恢复的节点所使用的替代节点使用相同的名称。

有关的位置的详细信息、请参见安装说明 `/var/local` 节点的卷。

.步骤
. 在已恢复主机的命令行中、列出当前已配置的所有StorageGRID 网格节点：``sudo storagegrid node list``
+
如果未配置网格节点，则不会显示任何输出。如果配置了某些网格节点，则输出格式应为：

+
[listing]
----
Name               Metadata-Volume
================================================================
dc1-adm1           /dev/mapper/sgws-adm1-var-local
dc1-gw1            /dev/mapper/sgws-gw1-var-local
dc1-sn1            /dev/mapper/sgws-sn1-var-local
dc1-arc1           /dev/mapper/sgws-arc1-var-local
----
+
如果未列出应在主机上配置的部分或全部网格节点，则需要还原缺少的网格节点。

. 导入具有的网格节点 `/var/local` 卷：
+
.. 对要导入的每个节点运行以下命令：``sudo storagegrid node import node-var-local-volume-path``
+
。 `storagegrid node import` 只有在目标节点上次运行的主机上已完全关闭时、命令才会成功。否则，您将看到类似以下内容的错误：

+
`This node (_node-name_) appears to be owned by another host (UUID host-uuid).`

+
`Use the --force flag if you are sure import is safe.`

.. 如果您看到有关节点归另一主机所有的错误、请使用重新运行命令 `--force` 用于完成导入的标志：``sudo storagegrid --force node import node-var-local-volume-path``
+

NOTE: 使用导入的任何节点 `--force` 该标志需要执行额外的恢复步骤、才能重新加入网格、如"`如果需要、执行其他恢复步骤"中所述。`



. 对于没有的网格节点 `/var/local` 卷中、重新创建节点的配置文件以将其还原到主机。
+
请按照安装说明中"`创建节点配置文件`"中的准则进行操作。

+

IMPORTANT: 重新创建节点的配置文件时，必须为要恢复的节点所使用的替代节点使用相同的名称。对于 Linux 部署，请确保配置文件名称包含节点名称。应尽可能使用相同的网络接口，块设备映射和 IP 地址。这种做法可以最大限度地减少恢复期间需要复制到节点的数据量，从而可以显著加快恢复速度（在某些情况下，只需几分钟而不是几周）。

+

IMPORTANT: 使用任何新的块设备(StorageGRID 节点先前未使用的设备)作为以开头的任何配置变量的值 `BLOCK_DEVICE_` 在为节点重新创建配置文件时、请务必遵循"`修复缺少的块设备错误"中的所有准则。`

. 在已恢复的主机上运行以下命令以列出所有 StorageGRID 节点。
+
`sudo storagegrid node list`

. 验证名称显示在 StorageGRID 节点列表输出中的每个网格节点的节点配置文件：
+
`sudo storagegrid node validate _node-name_`

+
在启动 StorageGRID 主机服务之前，您必须解决任何错误或警告。以下各节详细介绍了在恢复期间可能具有特殊意义的错误。



.相关信息
link:../rhel/index.html["安装 Red Hat Enterprise Linux 或 CentOS"]

link:../ubuntu/index.html["安装 Ubuntu 或 Debian"]

link:fixing-mssing-network-interface-errors.html["修复缺少的网络接口错误"]

link:fixing-missing-block-device-errors.html["修复缺少的块设备错误"]

link:whats-next-performing-additional-recovery-steps-if-required.html["下一步操作：如果需要、执行其他恢复步骤"]
