---
permalink: expand/copying-audit-logs.html 
sidebar: sidebar 
keywords: copy audit log, Admin Node expansion, 
summary: 通过扩展操作步骤 添加新管理节点时，其 AMS 服务仅会记录在加入系统后发生的事件和操作。您可以将审核日志从先前安装的管理节点复制到新的扩展管理节点、使其与StorageGRID 系统的其余部分保持同步。 
---
= 复制审核日志
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
通过扩展操作步骤 添加新管理节点时，其 AMS 服务仅会记录在加入系统后发生的事件和操作。您可以将审核日志从先前安装的管理节点复制到新的扩展管理节点、使其与StorageGRID 系统的其余部分保持同步。

.您需要的内容
* 要添加管理节点、您必须已完成所需的扩展步骤。
* 您必须具有 `Passwords.txt` 文件


.关于此任务
要使来自扩展管理节点上的其他管理节点的历史审核消息可用、必须手动将审核日志文件从主管理节点或其他现有管理节点复制到扩展管理节点。

.步骤
. 登录到主管理节点：
+
.. 输入以下命令： `ssh _admin@_primary_Admin_Node_IP_`
.. 输入中列出的密码 `Passwords.txt` 文件
.. 输入以下命令切换到root： `su -`
.. 输入中列出的密码 `Passwords.txt` 文件
+
以root用户身份登录后、提示符将从变为 `$` to `#`。



. 停止AMS服务以防止其创建新文件： `service ams stop`
. 重命名 `audit.log` file以确保它不会覆盖要将其复制到的扩展管理节点上的文件：
+
`cd /var/local/audit/export` +
`ls -l` +
`mv audit.log _new_name_.txt`

. 将所有审核日志文件复制到扩展管理节点：
+
`scp -p * _IP_address_:/var/local/audit/export`

. 如果提示输入的密码短语 `/root/.ssh/id_rsa`、输入中列出的主管理节点的SSH访问密码 `Passwords.txt` 文件
. 还原原始卷 `audit.log` 文件：
+
`mv _new_name_.txt audit.log`

. 启动 AMS 服务：
+
`service ams start`

. 从服务器注销：
+
`exit`

. 登录到扩展管理节点：
+
.. 输入以下命令： `ssh admin@_expansion_Admin_Node_IP_`
.. 输入中列出的密码 `Passwords.txt` 文件
.. 输入以下命令切换到root： `su -`
.. 输入中列出的密码 `Passwords.txt` 文件
+
以root用户身份登录后、提示符将从变为 `$` to `#`。



. 更新审核日志文件的用户和组设置：
+
`cd /var/local/audit/export` +
`chown ams-user:bycast *`

. 从服务器注销：
+
`exit`


