---
permalink: expand/preparing-for-expansion.html 
sidebar: sidebar 
keywords: expand, expansion, planning 
summary: 您必须通过获取所需材料以及安装和配置任何新硬件和网络为StorageGRID 扩展做好准备。 
---
= 准备扩展
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您必须通过获取所需材料以及安装和配置任何新硬件和网络为StorageGRID 扩展做好准备。



== 收集所需材料

在执行扩展操作之前、您必须收集下表中列出的材料。

[cols="1a,2a"]
|===
| 项目 | 注释： 


 a| 
StorageGRID 安装归档
 a| 
如果要添加新的网格节点或新站点，则必须下载并提取 StorageGRID 安装归档。您必须使用网格上当前运行的相同版本。

有关详细信息、请参见有关下载和提取StorageGRID 安装文件的说明。

* 注意： * 如果要向现有存储节点添加新存储卷或安装新的 StorageGRID 设备，则不需要下载文件。



 a| 
服务笔记本电脑
 a| 
服务笔记本电脑必须满足以下要求：

* 网络端口
* SSH 客户端（例如 PuTTY ）
* 支持的浏览器




 a| 
配置密码短语
 a| 
首次安装 StorageGRID 系统时，系统会创建并记录密码短语。配置密码短语不在中 `Passwords.txt` 文件



 a| 
StorageGRID 文档
 a| 
* _管理StorageGRID _
* StorageGRID 发行说明_
* 适用于您的平台的安装说明




 a| 
适用于您的平台的最新文档
 a| 
有关支持的版本，请参见互操作性表。

|===
.相关信息
link:../admin/index.html["管理 StorageGRID"]

link:../release-notes/index.html["发行说明"]

link:../vmware/index.html["安装 VMware"]

link:../rhel/index.html["安装 Red Hat Enterprise Linux 或 CentOS"]

link:../ubuntu/index.html["安装 Ubuntu 或 Debian"]

https://mysupport.netapp.com/matrix["NetApp 互操作性表工具"^]



=== Web 浏览器要求

您必须使用受支持的 Web 浏览器。

[cols="1a,1a"]
|===
| Web 浏览器 | 支持的最低版本 


 a| 
Google Chrome
 a| 
87



 a| 
Microsoft Edge
 a| 
87



 a| 
Mozilla Firefox
 a| 
84.

|===
您应将浏览器窗口设置为建议的宽度。

[cols="1a,1a"]
|===
| 浏览器宽度 | 像素 


 a| 
最小值
 a| 
1024



 a| 
最佳
 a| 
1280

|===


== 下载并提取StorageGRID 安装文件

在添加新网格节点或新站点之前，必须下载相应的 StorageGRID 安装归档并提取文件。

.关于此任务
您必须使用网格上当前运行的 StorageGRID 版本执行扩展操作。

.步骤
. 转到 StorageGRID 的 "NetApp 下载 " 页面。
+
https://mysupport.netapp.com/site/products/all/details/storagegrid/downloads-tab["NetApp 下载： StorageGRID"^]

. 选择网格上当前运行的 StorageGRID 版本。
. 使用您的 NetApp 帐户的用户名和密码登录。
. 阅读最终用户许可协议，选中复选框，然后选择 * 接受并继续 * 。
. 在下载页面的*安装StorageGRID *列中、选择 `.tgz` 或 `.zip` 适用于您的平台的文件。
+
安装归档文件中显示的版本必须与当前安装的软件版本匹配。

+
使用 `.zip` 如果您在服务笔记本电脑上运行Windows、则将文件保存。

+
[cols="1a,1a"]
|===
| 平台 | 安装归档 


 a| 
VMware
| StorageGRID-Webscale-_version_-VMware-_uniqueID_.zip StorageGRID-Webscale -_version_-vmware-_uniqueID_.tgz 


 a| 
Red Hat Enterprise Linux 或 CentOS
| StorageGRID-Webscale-_version_-RPM-_uniqueID_.zip StorageGRID-Webscale -_version_-RPM-_uniqueID_.tgz 


 a| 
Ubuntu或Debian及设备
| StorageGRID-Webscale-_version_-DEB-_uniqueID_.zip StorageGRID-Webscale -_version_-Deb-_uniqueID_.tgz 


 a| 
OpenStack/ 其他虚拟机管理程序
 a| 
要在 OpenStack 上扩展现有部署，您必须部署一个运行上述受支持 Linux 分发版本之一的虚拟机，并按照适用于 Linux 的相应说明进行操作。

|===
. 下载并提取归档文件。
. 按照适用于您的平台的步骤，根据您的平台，计划的网格拓扑以及您将如何扩展 StorageGRID 系统来选择所需的文件。
+
步骤中为每个平台列出的路径与归档文件安装的顶级目录相对。

. 如果要扩展 VMware 系统，请选择相应的文件。
+
[cols="1a,1a"]
|===
| 路径和文件名 | Description 


| ./vSphere/README  a| 
一个文本文件，用于描述 StorageGRID 下载文件中包含的所有文件。



| ./vSphere/NLF000000.txt  a| 
一种免费许可证，不提供产品的任何支持授权。



| ./vsphere/netapp-sg-_version_-sha.vmdk  a| 
用作创建网格节点虚拟机的模板的虚拟机磁盘文件。



| ./vSphere/vsphere-primary-admin.OVF ./vsphere/vsphere-primary-admin.mf  a| 
开放式虚拟化格式模板文件 (`.ovf`)和清单文件 (`.mf`)以部署主管理节点。



| ./vSphere/vsphere-non-primary-admin.OVF ./vsphere/vsphere-non-primary-admin.mf  a| 
模板文件 (`.ovf`)和清单文件 (`.mf`)以部署非主管理节点。



| ./vSphere/vsphere-archive.OVF ./vsphere/vsphere-archive.mf  a| 
模板文件 (`.ovf`)和清单文件 (`.mf`)以部署归档节点。



| ./vSphere/vsphere-gateway.OVF ./vsphere/vsphere-gateway.mf  a| 
模板文件 (`.ovf`)和清单文件 (`.mf`)以部署网关节点。



| ./vSphere/vsphere-storage.OVF ./vsphere/vsphere-storage.mf  a| 
模板文件 (`.ovf`)和清单文件 (`.mf`)以部署基于虚拟机的存储节点。



| 部署脚本工具 | Description 


| ./vSphere/deploy-vsphere-ovftool.sh  a| 
Bash shell 脚本，用于自动部署虚拟网格节点。



| ./vSphere/deploy-vsphere-ovftool-sample.ini  a| 
用于的示例配置文件 `deploy-vsphere-ovftool.sh` 脚本。



| ./vSphere/configure-storagegrid.py  a| 
一种用于自动配置 StorageGRID 系统的 Python 脚本。



| ./vSphere/configure-sga.py  a| 
一种用于自动配置 StorageGRID 设备的 Python 脚本。



| ./vSphere/storagegrid-ssoauth.py  a| 
一个示例 Python 脚本，启用单点登录后，您可以使用该脚本登录到网格管理 API 。



| ./vsphere/configure-storaggrid.sample.json  a| 
用于的示例配置文件 `configure-storagegrid.py` 脚本。



| ./vsphere/configure-storaggrid.blank.json  a| 
用于的空白配置文件 `configure-storagegrid.py` 脚本。

|===
. 如果要扩展 Red Hat Enterprise Linux 或 CentOS 系统，请选择相应的文件。
+
[cols="1a,1a"]
|===
| 路径和文件名 | Description 


| ./rpms/README  a| 
一个文本文件，用于描述 StorageGRID 下载文件中包含的所有文件。



| ./rpms/NLF000000.txt  a| 
一种免费许可证，不提供产品的任何支持授权。



| ./rpms/StorageGRID-Webscale-Images-version-SHA.rpm  a| 
RPM 软件包，用于在 RHEL 或 CentOS 主机上安装 StorageGRID 节点映像。



| ./rpms/StorageGRID-Webscale-Service-version-SHA.rpm  a| 
RPM 软件包，用于在 RHEL 或 CentOS 主机上安装 StorageGRID 主机服务。



| 部署脚本工具 | Description 


| ./rpms/configure-storagegrid.py  a| 
一种用于自动配置 StorageGRID 系统的 Python 脚本。



| ./rpms/configure-sga.py  a| 
一种用于自动配置 StorageGRID 设备的 Python 脚本。



| ./rpms/configure-storagegrid.sample.json  a| 
用于的示例配置文件 `configure-storagegrid.py` 脚本。



| ./rpms/storagegrid-ssoauth.py  a| 
一个示例 Python 脚本，启用单点登录后，您可以使用该脚本登录到网格管理 API 。



| ./rpms/configure-storagegrid.blank.json  a| 
用于的空白配置文件 `configure-storagegrid.py` 脚本。



| ./rpms/Extras 或 Ansible  a| 
用于为 StorageGRID 容器部署配置 RHEL 或 CentOS 主机的 Ansible 角色示例和攻略手册。您可以根据需要自定义角色或攻略手册。

|===
. 如果要扩展 Ubuntu 或 Debian 系统，请选择相应的文件。
+
[cols="1a,1a"]
|===
| 路径和文件名 | Description 


| /debs/README  a| 
一个文本文件，用于描述 StorageGRID 下载文件中包含的所有文件。



| ./debs/NLF000000.txt  a| 
非生产 NetApp 许可证文件，可用于测试和概念验证部署。



| ./debs/storagegrid-webscale-images-version-SHA.deb  a| 
用于在 Ubuntu 或 Debian 主机上安装 StorageGRID 节点映像的 Deb 软件包。



| ./debs/storagegrid-webscale-images-version-SHA.deb.md5  a| 
文件的MD5校验和 `/debs/storagegrid-webscale-images-version-SHA.deb`。



| ./debs/storagegrid-webscale-service-version-SHA.deb  a| 
用于在 Ubuntu 或 Debian 主机上安装 StorageGRID 主机服务的 Deb 软件包。



| 部署脚本工具 | Description 


| ./debs/configure-storagegrid.py  a| 
一种用于自动配置 StorageGRID 系统的 Python 脚本。



| ./debs/configure-sga.py  a| 
一种用于自动配置 StorageGRID 设备的 Python 脚本。



| ./debs/storagegrid-ssoauth.py  a| 
一个示例 Python 脚本，启用单点登录后，您可以使用该脚本登录到网格管理 API 。



| ./debs/configure-storaggrid.sample.json  a| 
用于的示例配置文件 `configure-storagegrid.py` 脚本。



| ./debs/configure-storaggrid.blank.json  a| 
用于的空白配置文件 `configure-storagegrid.py` 脚本。



| ./debs/Extras / Ansible  a| 
用于为 StorageGRID 容器部署配置 Ubuntu 或 Debian 主机的 Ansible 角色示例和攻略手册。您可以根据需要自定义角色或攻略手册。

|===
. 如果要扩展基于 StorageGRID 设备的系统，请选择相应的文件。
+
[cols="1a,1a"]
|===
| 路径和文件名 | Description 


| ./debs/storagegrid-webscale-images-version-SHA.deb  a| 
用于在设备上安装 StorageGRID 节点映像的 Deb 软件包。



| ./debs/storagegrid-webscale-images-version-SHA.deb.md5  a| 
StorageGRID 设备安装程序使用的 Deb 安装包的校验和，用于验证该软件包在上传后是否完好无损。

|===
+

NOTE: 对于设备安装，只有在需要避免网络流量时，才需要这些文件。设备可以从主管理节点下载所需文件。





== 验证硬件和网络连接

开始扩展StorageGRID 系统之前、您必须确保已安装并配置所需的硬件、以支持新的网格节点或新站点。

有关受支持版本的信息、请参见互操作性表。

您还必须验证站点上服务器之间的网络连接、并确认主管理节点可以与用于托管StorageGRID 系统的所有扩展服务器进行通信。

如果要执行的扩展活动包括添加新子网，则必须先添加新的网格子网，然后再启动扩展操作步骤 。

请勿在网格节点之间或 StorageGRID 站点之间的网格网络上使用网络地址转换（ Network Address Translation ， NAT ）。如果您对网格网络使用专用 IPv4 地址，则这些地址必须可从每个站点的每个网格节点直接路由。但是，您可以根据需要在外部客户端和网格节点之间使用 NAT ，例如为网关节点提供公有 IP 地址。只有在使用对网格中的所有节点都透明的通道应用程序时，才支持使用 NAT 桥接公有 网段，这意味着网格节点不需要了解公有 IP 地址。

* 相关信息 *

https://mysupport.netapp.com/matrix["NetApp 互操作性表工具"^]

link:updating-subnets-for-grid-network.html["更新网格网络的子网"]
