---
permalink: ilm/comparing-s3-object-lock-to-legacy-compliance.html 
sidebar: sidebar 
keywords:  
summary:  
---
= 比较 S3 对象锁定与原有合规性
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID 11.5中的S3对象锁定功能取代了先前StorageGRID 版本中提供的合规性功能。由于新的S3对象锁定功能符合Amazon S3要求、因此它会弃用专有的StorageGRID 合规性功能、现在称为"`原有合规性"。`

如果先前启用了全局合规性设置、则在升级到StorageGRID 11.5时、新的全局S3对象锁定设置将自动启用。租户用户将无法再创建在StorageGRID 11.5中启用了合规性的新分段；但是、根据需要、租户用户可以继续使用和管理任何现有的旧合规分段、其中包括执行以下任务：

* 将新对象载入已启用旧合规性的现有存储分段。
* 增加启用了旧合规性的现有存储分段的保留期限。
* 更改已启用旧合规性的现有存储分段的自动删除设置。
* 对已启用旧合规性的现有存储分段置于合法保留状态。
* 取消合法保留。


https://["NetApp 知识库：如何在 StorageGRID 11.5 中管理原有的合规存储分段"^]

如果您在先前版本的 StorageGRID 中使用了原有的合规性功能，请参见下表，了解它与 StorageGRID 中的 S3 对象锁定功能的比较情况。

[cols="1a,1a,1a"]
|===
|  | S3 对象锁定（新增） | 合规性（原有） 


 a| 
如何全局启用此功能？
 a| 
在网格管理器中、选择*配置*>*系统设置*>* S3对象锁定*。
 a| 
不再支持。

*注意：*如果先前启用了全局合规性设置、则在升级到StorageGRID 11.5时、全局S3对象锁定设置将自动启用。



 a| 
如何为存储分段启用此功能？
 a| 
在使用租户管理器，租户管理 API 或 S3 REST API 创建新存储分段时，用户必须启用 S3 对象锁定。
 a| 
用户无法再在启用了合规性的情况下创建新的存储分段；但是，他们可以继续向现有合规存储分段添加新对象。



 a| 
是否支持存储分版本控制？
 a| 
是的。需要分段版本控制，并且在为分段启用 S3 对象锁定时会自动启用分段版本控制。
 a| 
否原有的合规性功能不允许分段版本控制。



 a| 
如何设置对象保留？
 a| 
用户可以为每个对象版本设置保留截止日期。
 a| 
用户必须为整个存储分段设置一个保留期限。保留期限适用场景 存储分段中的所有对象。



 a| 
存储分段是否具有保留和合法保留的默认设置？
 a| 
否启用了S3对象锁定的StorageGRID 分段没有默认保留期限。而是可以为每个对象版本指定保留截止日期。
 a| 
是的。



 a| 
是否可以更改保留期限？
 a| 
对象版本的保留日期可以增加，但不能减少。
 a| 
存储分段的保留期限可以增加，但不能缩短。



 a| 
合法保留在何处？
 a| 
用户可以对存储分段中的任何对象版本进行合法保留或取消合法保留。
 a| 
合法保留放置在存储分段上，并影响存储分段中的所有对象。



 a| 
何时可以删除对象？
 a| 
如果对象未处于合法保留状态，则可以在达到保留截止日期后删除该对象版本。
 a| 
可以在保留期限到期后删除对象，前提是存储分段未处于合法保留状态。可以自动或手动删除对象。



 a| 
是否支持存储分段生命周期配置？
 a| 
是的。
 a| 
否

|===