---
permalink: ilm/how-s3-versioned-objects-are-deleted.html 
sidebar: sidebar 
keywords:  
summary: 如果为 S3 存储分段启用了版本控制，则无论这些请求来自 S3 客户端， S3 存储分段生命周期到期还是 ILM 策略要求， StorageGRID 都会在响应删除请求时遵循 Amazon S3 的行为。 
---
= 如何删除受版本控制的 S3 对象
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果为 S3 存储分段启用了版本控制，则无论这些请求来自 S3 客户端， S3 存储分段生命周期到期还是 ILM 策略要求， StorageGRID 都会在响应删除请求时遵循 Amazon S3 的行为。

对对象进行版本控制时，对象删除请求不会删除对象的当前版本，也不会释放空间。相反，对象删除请求只会创建一个删除标记作为对象的当前版本，从而使先前版本的对象 "`noncurrent.` " 成为非最新版本。

即使尚未删除此对象， StorageGRID 的行为仍会使当前版本的对象不再可用。对该对象的请求将返回 404 NotFound 。但是，由于未删除非当前对象数据，因此指定非当前对象版本的请求可能会成功。

要在删除受版本控制的对象时释放空间，必须执行以下操作之一：

* * S3客户端请求*：在S3删除对象请求中指定对象版本号 (`DELETE /object?versionId=ID`）。请注意，此请求仅删除指定版本的对象副本（其他版本仍占用空间）。
* *分段生命周期*：使用 `NoncurrentVersionExpiration` 存储分段生命周期配置中的操作。满足指定的非当前磁盘数后， StorageGRID 将永久删除非当前对象版本的所有副本。无法恢复这些对象版本。
* * ILM ：向 ILM 策略添加两个 ILM 规则。在第一个规则中使用 * 非当前时间 * 作为参考时间，以匹配对象的非当前版本。在第二个规则中使用 * 载入时间 * 以匹配当前版本。必须在 * 载入时间 * 规则上方的策略中显示 * 非当前时间 * 规则。


.相关信息
link:../s3/index.html["使用 S3"]

link:example-4-ilm-rules-and-policy-for-s3-versioned-objects.html["示例 4 ： S3 版本对象的 ILM 规则和策略"]
