---
permalink: fabricpool/best-practices-for-high-availability-groups.html 
sidebar: sidebar 
keywords: fabricPool, high availability group, HA group, active-active, active-backup, cloud tier, best practices 
summary: '在将StorageGRID 附加为FabricPool 云层之前、您可以使用StorageGRID 网格管理器配置高可用性\(HA\)组。' 
---
= 高可用性组的最佳实践
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在将StorageGRID 附加为FabricPool 云层之前、您可以使用StorageGRID 网格管理器配置高可用性(HA)组。



== 什么是高可用性(HA)组

为了确保负载平衡器服务始终可用于管理 FabricPool 数据，您可以将多个管理节点和网关节点的网络接口分组到一个实体中，称为高可用性（ High Availability ， HA ）组。如果 HA 组中的活动节点发生故障，则组中的另一个节点可以继续管理工作负载。

每个 HA 组均可提供对关联节点上共享服务的高可用性访问。例如、由所有管理节点组成的HA组可提供对某些管理节点管理服务和负载平衡器服务的高可用性访问。仅包含网关节点或管理节点和网关节点的HA组可提供对共享负载平衡器服务的高可用性访问。

创建HA组时、您可以选择属于网格网络(eth0)或客户端网络(eth2)的网络接口。HA组中的所有接口必须位于同一网络子网中。

HA组维护一个或多个虚拟IP地址、这些地址会添加到组中的活动接口中。如果活动接口不可用、则虚拟IP地址将移至另一个接口。此故障转移过程通常只需几秒钟，并且速度足以使客户端应用程序不会受到任何影响，并且可以依靠正常的重试行为继续运行。

如果您配置了一个由负载平衡节点组成的HA组、则FabricPool 会连接到该HA组的虚拟IP地址。



== 高可用性（ HA ）组的最佳实践

为 FabricPool 创建 StorageGRID HA 组的最佳实践取决于工作负载，如下所示：

* 如果您计划将 FabricPool 与主工作负载数据结合使用，则必须创建一个至少包含两个负载平衡节点的 HA 组，以防止数据检索中断。
* 如果您计划使用 FabricPool snapshot-only 卷分层策略或非主本地性能层（例如，灾难恢复位置或 NetApp SnapMirror ® 目标），则只能为 HA 组配置一个节点。


以下说明介绍如何为主动备份 HA 设置 HA 组（一个节点为活动节点，一个节点为备份节点）。但是，您可能更喜欢使用 DNS 轮循或主动 - 主动 HA 。要了解这些其他 HA 配置的优势，请参见 link:../admin/configuration-options-for-ha-groups.html["HA 组的配置选项"]。
