---
permalink: fabricpool/best-practices-for-load-balancing.html 
sidebar: sidebar 
keywords: fabricPool, load balancer, endpoint, load balancing, Layer 7, cloud tier, best practices 
summary: 在将StorageGRID 附加为FabricPool 云层之前、您可以使用StorageGRID 网格管理器至少配置一个负载平衡器端点。 
---
= 负载平衡最佳实践
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在将StorageGRID 附加为FabricPool 云层之前、您可以使用StorageGRID 网格管理器至少配置一个负载平衡器端点。



== 什么是负载平衡

在将数据从 FabricPool 分层到 StorageGRID 系统时， StorageGRID 会使用负载平衡器来管理载入和检索工作负载。负载平衡通过在多个存储节点之间分布 FabricPool 工作负载，最大限度地提高速度和连接容量。

StorageGRID 负载平衡器服务安装在所有管理节点和所有网关节点上，并提供第 7 层负载平衡。它会终止客户端请求，检查请求并与存储节点建立新的安全连接。

将客户端流量转发到存储节点时，每个节点上的负载平衡器服务会独立运行。通过加权过程，负载平衡器服务会将更多请求路由到 CPU 可用性更高的存储节点。

虽然建议使用 StorageGRID 负载平衡器服务来平衡负载，但您可能希望集成第三方负载平衡器。有关信息、请联系您的NetApp客户代表或参阅以下技术报告：

https://www.netapp.com/pdf.html?item=/media/17068-tr4626pdf.pdf["StorageGRID 负载平衡器选项"^]


NOTE: 网关节点上的单独连接负载平衡器（ CLB ）服务已弃用，不再建议用于 FabricPool 。



== StorageGRID 负载平衡最佳实践

作为一般最佳实践， StorageGRID 系统中的每个站点都应包含两个或更多具有负载平衡器服务的节点。例如、一个站点可能同时包含一个管理节点和一个网关节点、甚至包括两个管理节点。无论您使用的是 SG100 或 SG1000 服务设备，裸机节点还是基于虚拟机（ VM ）的节点，确保每个负载平衡节点都有足够的网络，硬件或虚拟化基础架构。

您必须配置 StorageGRID 负载平衡器端点，以定义网关节点和管理节点用于传入和传出 FabricPool 请求的端口。



== 负载平衡器端点证书的最佳实践

创建用于FabricPool 的负载平衡器端点时、必须使用HTTPS作为协议。然后、您可以上传由公共信任或私有证书颁发机构(CA)签名的证书、也可以生成自签名证书。此证书允许 ONTAP 向 StorageGRID 进行身份验证。

作为最佳实践，您应使用 CA 服务器证书来保护连接。由 CA 签名的证书可以无中断地轮换。

请求用于负载平衡器端点的 CA 证书时，请确保此证书上的域名与您在 ONTAP 中为该负载平衡器端点输入的服务器名称匹配。如果可能，请使用通配符（ * ）来支持虚拟主机模式的 URL 。例如：

[listing]
----
*.s3.storagegrid.company.com
----
在将 StorageGRID 添加为 FabricPool 云层时，必须将同一证书安装到 ONTAP 集群以及根证书颁发机构（ CA ）证书和任何从属证书颁发机构（ CA ）证书。


NOTE: StorageGRID 将服务器证书用于多种用途。如果要连接到负载平衡器服务、则无需上传对象存储API服务端点服务器证书。

要了解有关负载平衡端点的服务器证书的详细信息，请执行以下操作：

* link:../admin/managing-load-balancing.html["管理负载平衡"]
* link:../harden/hardening-guideline-for-server-certificates.html["服务器证书的强化准则"]

