---
permalink: fabricpool/using-storagegrid-ilm-with-fabricpool-data.html 
sidebar: sidebar 
keywords: FabricPool, requirements, ILM, information lifecycle management, ILM rule, ILM rules, ILM policy, erasure-coding, replication, cloud storage pool, glacier 
summary: 如果您使用 FabricPool 将数据分层到 StorageGRID ，则必须了解创建 StorageGRID 信息生命周期管理 \ （ ILM ）规则以及用于管理 FabricPool 数据的 ILM 策略的要求。您必须确保适用于 FabricPool 数据的 ILM 规则不会造成中断。 
---
= 将StorageGRID 信息生命周期管理与FabricPool 数据结合使用
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您使用 FabricPool 将数据分层到 StorageGRID ，则必须了解创建 StorageGRID 信息生命周期管理（ ILM ）规则和用于管理 FabricPool 数据的 ILM 策略的要求。您必须确保适用于 FabricPool 数据的 ILM 规则不会造成中断。

[IMPORTANT]
====
FabricPool 不了解 StorageGRID ILM 规则或策略。如果 StorageGRID ILM 策略配置不当，可能会发生数据丢失。

了解更多信息： link:../ilm/index.html["使用 ILM 管理对象"]

====


== FabricPool 数据的ILM准则

请查看这些准则，以确保您的 ILM 规则和 ILM 策略适合 FabricPool 数据和业务要求。如果您已经在使用 StorageGRID ILM ，则可能需要更新活动的 ILM 策略以满足这些准则。

* 您可以使用复制和纠删编码规则的任意组合来保护云层数据。
+
建议的最佳实践是，在站点内使用 2+1 纠删编码，以实现经济高效的数据保护。与复制相比、纠删编码占用的CPU更多、但存储容量却显著减少。4+1和6+1方案使用的容量小于2+1、但在网格扩展期间添加存储节点时、会降低吞吐量并降低灵活性。

* 应用于 FabricPool 数据的每个规则都必须使用纠删编码，或者必须至少创建两个复制副本。
+

IMPORTANT: 如果 ILM 规则在任何时间段内仅创建一个复制副本，则会使数据面临永久丢失的风险。如果某个对象只存在一个复制副本，则在存储节点出现故障或出现严重错误时，该对象将丢失。在升级等维护过程中，您还会暂时失去对对象的访问权限。

* 请勿使用将使 FabricPool 云层数据过期或删除的 ILM 规则。将每个 ILM 规则中的保留期限设置为 " 永久 " ，以确保 StorageGRID ILM 不会删除 FabricPool 对象。
* 请勿创建将 FabricPool 云层数据从存储分段移至其他位置的规则。您不能使用ILM规则使用归档节点将FabricPool 数据归档到磁带、也不能使用云存储池将FabricPool 数据移动到Glacier。
+

NOTE: 不支持将云存储池与 FabricPool 结合使用，因为从云存储池目标检索对象会增加延迟。

* 从 ONTAP 9.8 开始，您可以选择创建对象标记来帮助对分层数据进行分类和排序，以便于管理。例如，您只能在连接到 StorageGRID 的 FabricPool 卷上设置标记。然后，在 StorageGRID 中创建 ILM 规则时，您可以使用对象标记高级筛选器选择并放置此数据。

